import Head from 'next/head';
import { Box, Flex, Heading, SimpleGrid, Text } from '@chakra-ui/react';
import Container from '../../components/container';
import MainLayout from '../../components/layout';
import { fetchStrapi } from '../../lib/api';
import HeroPostCard from '../../components/hero-post-card';
import PostCard from '../../components/post-card';
import CategorySideNav from '../../components/category-sidenav';

export default function Blog({ articles, allArticleCategories }) {
  return (
    <Container>
      <Head>
        <title>Blog - Tech Corner</title>
        <meta name="description" content="Generated by create next app" />
        <link rel='icon' href='/favicon.png' />
      </Head>
      <MainLayout>
        <Flex mt={12} w='100%' flexWrap="wrap" >
          <CategorySideNav title='Topics' categories={allArticleCategories} pathPrefix={`/blog/topic`} mb={8} mr={24} minWidth="200px" />
          <Box maxWidth='800px'>
            <Heading as='h1' mb='1.5rem' color='#353535'>
              Latest Posts
            </Heading>
            <Flex gridColumnGap="2rem" gridRowGap="1.5rem" flexWrap="wrap" width="100%">
              <HeroPostCard {...articles[0]}></HeroPostCard>
              <Flex flex="0 1 auto" flexDirection="row" flexWrap="wrap" margin="0 -.8rem">
                {
                  articles.slice(1, articles.length).map((post) => {
                    return (

                      <PostCard key={post.id} {...post} />
                    )
                  })
                }
              </Flex>
            </Flex>
          </Box>
        </Flex>
      </MainLayout>
    </Container>
  )
}

export async function getStaticProps() {
  const articles = await fetchStrapi("get.articles");
  const allArticleCategories = await fetchStrapi("get.article-categories");

  return {
    props: {
      articles,
      allArticleCategories
    },
  };
}
