import Head from 'next/head';
import { Flex, Heading, Stack, Text, Image } from '@chakra-ui/react';

import Container from '../components/container';

export default function Home() {
	return (
		<Container>
			<Head>
				<title>Home - Tech Corner</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Flex
                justifyContent='center'
                bg='white'
                w="100%"
                pt="100px"
                pb="64px">
                <Stack spacing={16} direction={['column', 'row']} width="100%" px='4rem' maxWidth="1120px" maxHeight="300px">
					<Flex>
                    <Heading as="h1" mb={2} color="#353535" fontSize="4xl">Home</Heading>
					</Flex>
					<Image boxSize="250px" objectFit="contain" src="/images/hero-img.jpg" alt="hero" />
                </Stack>
            </Flex>
        </Container>
    );
}
