import { HStack, Text, Heading } from '@chakra-ui/react'
import Head from 'next/head'
import Image from 'next/image'

import Container from '../../components/container'
import { SingleTopicButton, SingleTopicCard } from '../../components/single-topic-btn'
import NoteSectionContainer from '../../components/note-section-container'

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Notes - Tech Corner</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HStack
       spacing={8}
       mb={8}>
        <SingleTopicButton topic="Breadth First Search Super Uber long" to="/"/>
        <SingleTopicButton topic="Breadth First Search" to="/"/>
      </HStack>
      <HStack
        spacing={8}
        mb={8}>
        <SingleTopicCard topic="Big O Notation" category="Algorithms"/>
        <SingleTopicCard topic="Time Complexity" category="Algorithms"/>
        <SingleTopicCard topic="Space Complexity with more" category="Algorithms"/>
      </HStack>
      <NoteSectionContainer>
        <Heading
          fontSize="lg"
          fontWeight="semibold"
          color="#353535">
          What is Big Oh Notation?
        </Heading>
        <Text
          fontSize="sm"
          color="#686868">
          Hello world...
        </Text>
      </NoteSectionContainer>

    </Container>
  )
}
